"use client";
import React from "react";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

type SummaryShape = {
  id?: number;
  title?: string | null;
  summaryText?: string | null;
  createdAt?: string | Date | null;
  fileName?: string | null;
  originFileUrl?: string | null;
};

export default function DownloadSummaryButton({
  summary,
}: {
  summary: SummaryShape;
}) {
  const handleDownload = () => {
    const created = summary.createdAt
      ? new Date(summary.createdAt).toLocaleString()
      : "Unknown date";

    const summaryContent = `# ${
      summary.title || "Untitled Summary"
    }\n\nGenerated Summary\nGenerated on: ${created}\n\n${
      summary.summaryText || ""
    }\n\nOriginal file: ${
      summary.fileName || "Unknown file"
    }\nGenerated by EverythingAI`;

    const blob = new Blob([summaryContent], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `summary-${summary.id ?? "untitled"}.txt`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <Button onClick={handleDownload} aria-label="Download summary">
      <Download className="h-4 w-4 inline-block mr-1" />
      Download Summary
    </Button>
  );
}
